FROM nginx:latest

RUN apt-get update && apt-get install -y certbot python3-certbot-nginx

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
COPY proxy_params /etc/nginx

CMD ["certbot", "--nginx", "-d", "site.mydemo-site.ru", "--register-unsafely-without-email", "--agree-tos", "--redirect"]