version: "2"

services:
  database:
    image: postgres:15
    restart: always
    container_name: shop_postgres
    volumes:
      - ~/.pg/pg_data/shop:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
  shop:
    build: 
      dockerfile: Dockerfile
      context: .
    image: shop_docker:latest
    container_name: shop_docker
    depends_on:
      - database
    volumes:
      - static_volume:/shop/static
      - media_volume:/shop/media
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${ALLOWED_HOST}
      - LETSENCRYPT_HOST=${ALLOWED_HOST}
    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py migrate  && gunicorn -b 0.0.0.0:8000 shop.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: shop_nginx
    image: shop_nginx
    volumes:
      - static_volume:/shop/static
      - media_volume:/shop/media
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - shop
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
      - "443:443"
  acme_companion:
    image: nginxproxy/acme-companion:2.2
    container_name: shop_acme_companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh



volumes:
  static_volume:
  media_volume:
  certs:
  vhost:
  html:
  acme: