# Generated by Django 4.2.4 on 2023-09-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_old_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='total',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('rejected', 'rejected'), ('in_review', 'In review'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
    ]
