# Generated by Django 4.2.4 on 2023-09-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cartorder_price_alter_cartorderitems_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('rejected', 'rejected'), ('in_review', 'In review'), ('disabled', 'Disabled'), ('published', 'Published')], default='in_review', max_length=10),
        ),
    ]
