# Generated by Django 4.2.4 on 2023-09-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_payment_to_pay_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='charge_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
