# Generated by Django 4.2.4 on 2023-09-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_payment_charge_id_alter_product_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='charge_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='draft', max_length=10),
        ),
    ]
