# Generated by Django 4.2.4 on 2023-09-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='country',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
