# Generated by Django 4.2.4 on 2023-09-27 20:41

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFG12345', length=10, max_length=30, prefix='order', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('disabled', 'Disabled')], default='draft', max_length=10),
        ),
    ]
