# Generated by Django 4.2.4 on 2023-11-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_product_specifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accessories',
            field=models.TextField(blank=True, default='Поле может быть пустым. Иначе введите список комплектации с помощью переноса строки.', null=True),
        ),
    ]
