# Generated by Django 4.2.4 on 2023-11-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_product_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accessories_en',
            field=models.TextField(blank=True, default='Поле может быть пустым. Иначе введите список комплектации с помощью переноса строки.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='accessories_ru',
            field=models.TextField(blank=True, default='Поле может быть пустым. Иначе введите список комплектации с помощью переноса строки.', null=True),
        ),
    ]
